// ─── Resource: Theme System ──────────────────────────────────────────────────

export function getThemeContent(): string {
  return `# Theme System — @e-burgos/tucu-ui

## useTheme Hook
Central hook for programmatic theme access. Powered by Zustand with a \`persist\`
middleware (\`ui/tucu-ui/src/themes/hooks/use-theme.tsx\`) — every field below except
\`isSettingsOpen\` is written to \`localStorage\` on every change (see Persistence below).

### State Properties
The store holds **24 preset slots**, not just the 4 you'd style a button with — status
and foreground/border colors are themeable too:

\`\`\`typescript
interface IThemeState {
  mode: 'light' | 'dark';
  colorScheme: 'default' | 'macos' | 'macos-tahoe';
  layout: LAYOUT_OPTIONS;
  direction: 'ltr' | 'rtl';
  lang: 'en' | 'es' | 'fr';
  primaryPreset: IThemeItem;
  darkPrimaryPreset: IThemeItem;
  secondaryPreset: IThemeItem;
  darkSecondaryPreset: IThemeItem;
  accentPreset: IThemeItem;
  darkAccentPreset: IThemeItem;
  mutedPreset: IThemeItem;
  darkMutedPreset: IThemeItem;
  darkBgPreset: IThemeItem;
  lightBgPreset: IThemeItem;
  lightDarkPreset: IThemeItem;
  darkLightDarkPreset: IThemeItem;
  successPreset: IThemeItem;
  darkSuccessPreset: IThemeItem;
  warningPreset: IThemeItem;
  darkWarningPreset: IThemeItem;
  errorPreset: IThemeItem;
  darkErrorPreset: IThemeItem;
  infoPreset: IThemeItem;
  darkInfoPreset: IThemeItem;
  fgPreset: IThemeItem;
  darkFgPreset: IThemeItem;
  borderPreset: IThemeItem;
  darkBorderPreset: IThemeItem;
  logo: LogoType;
  showSettings: boolean;
  isSettingsOpen: boolean;
  backgroundVariant: 'none' | 'base' | 'sonoma' | 'wave' | 'wallpaper' | 'mobile' | 'radial' | 'window' | 'aurora' | 'depth' | 'demo';
  themeConfigs: Record<'default' | 'macos' | 'macos-tahoe', IThemeConfig>; // IThemeConfig mirrors every *Preset field above + layout/mode/direction/backgroundVariant
}
\`\`\`
// ui/tucu-ui/src/themes/hooks/use-theme.tsx

### Setters (auto-generated for every field above except \`themeConfigs\`)
\`setMode\`, \`setLayout\`, \`setColorScheme\`, \`setDirection\`, \`setLang\`, \`setPrimaryPreset\`,
\`setDarkPrimaryPreset\`, \`setSecondaryPreset\`, \`setAccentPreset\`, \`setSuccessPreset\`,
\`setErrorPreset\`, \`setBorderPreset\`, \`setBackgroundVariant\`, etc. — one \`set<Field>\` per
state key, generated by \`createSetters\` from the default state's keys.

### Actions
| Method | Description |
|--------|-------------|
| restoreDefaultColors() | Resets every preset + layout, mode, direction, backgroundVariant for the ACTIVE colorScheme back to their defaults |
| applyMacOSTheme() | Switches colorScheme to 'macos' (loads its saved config) |
| applyMacOSTahoeTheme() | Switches colorScheme to 'macos-tahoe' (loads its saved config) |
| applyDefaultTheme() | Switches colorScheme to 'default' (loads its saved config) |
| applyThemeStyle(style) | Switches colorScheme to the given style (loads its saved themeConfigs entry) |

### Theme Configuration State Sync
A Zustand middleware (\`themeConfigInterceptor\`) intercepts every \`set()\`/\`setState()\`
call. When the update touches a "config key" (any preset, \`layout\`, \`mode\`,
\`direction\`, \`backgroundVariant\` — 28 keys), it is mirrored into
\`themeConfigs[activeColorScheme]\` automatically — you never write to \`themeConfigs\`
yourself. When \`colorScheme\` changes (e.g. via \`applyMacOSTheme()\`), the interceptor
loads that scheme's saved config back onto the root state in the same update, so each
variant remembers its own last-used layout, presets, mode and background.

### Persistence — what's saved, and its gotchas
The store persists to \`localStorage\` under the key **\`theme-storage\`**
(\`persist(..., { name: 'theme-storage', partialize })\` —
\`ui/tucu-ui/src/themes/hooks/use-theme.tsx\`).

- **\`partialize\` drops \`isSettingsOpen\`** (transient UI state), filters out every
  function, and **nulls out \`logo.logo\`** before serializing — if you pass a React node
  as part of \`logo\`, it is intentionally not persisted (React nodes aren't
  serializable); only the rest of the logo config round-trips.
- **There is no \`version\`/\`migrate\` on the persist config.** A future breaking change
  to the persisted shape will land on top of whatever old shape is in the user's
  localStorage — if you see inconsistent theme state after an upgrade, clearing the
  \`theme-storage\` key is the reset path.
- ThemeProvider props interact with persistence like this: \`mode\`, \`layout\`,
  \`background\` and \`brandColor\` are re-applied on EVERY page load, so passing them pins
  the value and silently overrides whatever the user saved in the settings drawer. Omit
  them (and pass \`showSettings\`) when user preferences should win.

### Usage
\`\`\`tsx
import { useTheme, LAYOUT_OPTIONS } from '@e-burgos/tucu-ui';

const ThemeControls = () => {
  const {
    mode, setMode,
    layout, setLayout,
    colorScheme, applyMacOSTheme, applyDefaultTheme,
    direction, setDirection,
    restoreDefaultColors,
  } = useTheme();

  return (
    <div className="flex gap-4">
      <button onClick={() => setMode(mode === 'dark' ? 'light' : 'dark')}>
        Toggle Mode
      </button>
      <button onClick={() => setLayout(LAYOUT_OPTIONS.ADMIN)}>
        Admin Layout
      </button>
      <button onClick={colorScheme === 'macos' ? applyDefaultTheme : applyMacOSTheme}>
        Switch Theme
      </button>
      <button onClick={restoreDefaultColors}>Reset</button>
    </div>
  );
};
\`\`\`

## ThemeProvider Setup
\`\`\`tsx
import { ThemeProvider } from '@e-burgos/tucu-ui';

function App() {
  return (
    <ThemeProvider
      showSettings               // shows the built-in settings drawer UI
      mode="dark"                 // 'light' | 'dark' — no 'system' value; resolve the OS preference yourself before this prop if you need it
      logo={{ name: 'My', secondName: 'App' }}
      menuItems={menuItems}
      isAuthenticated={isAuthenticated} // required
      loginUrl="/login"
    />
  );
}
\`\`\`
See \`tucu://shell\` for the standalone vs. MFE prop shapes, what \`ThemeProvider\`
mounts internally (its own \`BrowserRouter\` + the real scroll container), and the
\`rightButton\` header slot.

## Settings Components
| Component | Description |
|-----------|-------------|
| ThemeProvider | Entry point — wraps app with theme context, routing and layout |
| SettingsDrawer | Full settings panel (mode, preset, layout, direction, background) |
| SettingsButton | Floating gear button — see the load-bearing note below |
| SwitchMode | Inline light/dark toggle |
| LangSelector | Language dropdown (en, es, fr) |

**\`SettingsButton\` is not purely cosmetic.** \`ThemeWrapper\` always renders
\`<SettingsButton />\` and \`<SettingsDrawer />\`
(\`ui/tucu-ui/src/themes/components/theme-provider/theme-wrapper.tsx\`), and
\`SettingsButton\` is where the store's presets get applied to the DOM: it is the only
call site of \`useThemeColor(...)\`
(\`ui/tucu-ui/src/themes/hooks/use-theme-color.ts\`), whose effect writes every preset
into the matching \`--color-semantic-*\` CSS custom property on
\`document.documentElement\` (e.g. \`primaryPreset\` → \`--color-semantic-bg-primary\`,
which \`--color-primary\`/\`bg-primary\` alias). This is the mechanism behind every
"reactive to X" note in the \`customPaletteColor\` table below — there is no other code
path that retints these tokens live.

## \`customPaletteColor\` — the 24 keys, and the blast radius of each

\`customPaletteColor\` (a \`ThemeWrapper\`/\`ThemeProvider\` prop) is the declarative way to
brand an app without calling \`useTheme\` setters by hand. Every key maps 1:1 to one of
the 24 preset slots in the store above via \`PALETTE_MAP\`
(\`ui/tucu-ui/src/themes/components/theme-provider/theme-wrapper.tsx\`), applied once on
mount:

| \`customPaletteColor\` key | Store field | CSS variable written | Blast radius |
|---|---|---|---|
| \`primary\` / \`darkPrimary\` | \`primaryPreset\` / \`darkPrimaryPreset\` | \`--color-semantic-bg-primary\` (+dark) | Every primary/brand-colored surface: \`bg-primary\`/\`bg-brand\` (buttons, active nav \`bg-brand\`, macOS sidebars/widgets, file-input, input color tables), \`text-primary\` (Logo, Typography, cards) — **and \`bg-info\`, which aliases primary, see \`tucu://tokens\`**. Total — this is what "your brand color" means everywhere |
| \`secondary\` / \`darkSecondary\` | \`secondaryPreset\` / \`darkSecondaryPreset\` | \`--color-semantic-bg-secondary\` (+dark) | Narrower than the name implies: no component uses the \`bg-secondary\` utility directly; consumers are code that reads \`--color-semantic-bg-secondary\`/\`--color-secondary\` as variables (DataTable's \`--color-table-secondary\`, macOS surfaces) |
| \`accent\` / \`darkAccent\` | \`accentPreset\` / \`darkAccentPreset\` | \`--color-semantic-accent-bold-yellow\` (+dark) | \`bg-accent\`/\`text-accent\` DO alias this variable (\`theme.css\`), so the utility is reactive — but no core component consumes \`bg-accent\` today; the visible accent consumers are macOS Tahoe components via their own variables |
| \`muted\` / \`darkMuted\` | \`mutedPreset\` / \`darkMutedPreset\` | \`--color-semantic-fg-muted\` (+dark) | \`bg-muted\`/\`text-muted\` across every form input (switch, radio, pin-code, select, textarea, input, checkbox), helper/disabled text |
| \`darkBg\` / \`lightBg\` | \`darkBgPreset\` / \`lightBgPreset\` | \`--color-semantic-dark-bg\` / \`--color-semantic-bg\` | The page's own primary background per mode (feeds \`--color-body\`/\`bg-body\` — the real page background, see \`tucu://shell\`) |
| \`lightDark\` / \`darkLightDark\` | \`lightDarkPreset\` / \`darkLightDarkPreset\` | \`--color-semantic-bg-secondary-wash\` (+dark) | \`bg-light-dark\` — sidebars, table headers, hover states, elevated surfaces |
| \`success\` / \`darkSuccess\` | \`successPreset\` / \`darkSuccessPreset\` | \`--color-semantic-bg-positive\` (+dark) | Success \`Alert\`/\`Badge\`/\`Toast\` variants (\`bg-success\`) |
| \`warning\` / \`darkWarning\` | \`warningPreset\` / \`darkWarningPreset\` | \`--color-semantic-bg-warning\` (+dark) | Warning status variants (\`bg-warning\`) |
| \`error\` / \`darkError\` | \`errorPreset\` / \`darkErrorPreset\` | \`--color-semantic-bg-negative\` (+dark) | Error/danger status variants (\`bg-error\`), form validation error text |
| \`info\` / \`darkInfo\` | \`infoPreset\` / \`darkInfoPreset\` | \`--color-semantic-bg-info\` (+dark) | **Near zero through utilities: the \`bg-info\` Tailwind utility does NOT read this variable** — \`--color-info\` aliases \`--color-semantic-bg-primary\` instead (\`theme.css\`), so \`bg-info\` follows \`primary\`, and \`infoPreset\` only affects code reading \`--color-semantic-bg-info\` directly. See \`tucu://tokens\` |
| \`fg\` / \`darkFg\` | \`fgPreset\` / \`darkFgPreset\` | \`--color-semantic-fg\` (+dark) | Default foreground/text color (\`text-foreground\` via \`--font-primary-color\`) — second only to \`primary\` in reach |
| \`border\` / \`darkBorder\` | \`borderPreset\` / \`darkBorderPreset\` | \`--color-semantic-line-primary-subtle\` (+dark) | \`border-border\` — used by 50+ component files: cards, inputs, dividers, layout borders |

**Read this table as a warning, not just a reference.** \`primary\`, \`fg\`, \`border\` and
the two background washes are consumed by dozens of components each — an app that
overrides only \`primary\` and expects the rest of the design system to "just look
branded" will find backgrounds, borders and body text still on tucu-ui's defaults.
Full re-branding means setting those five (plus their \`dark*\` counterparts), not just
\`primary\`.

Each value accepts either a named preset label or a raw color string — an unrecognized
string falls back to being used as the literal value rather than resolved against
\`colorPreset\` (\`resolveColor\` in \`theme-wrapper.tsx\`). Note the lookup runs against
the 46-entry \`colorPreset\` array only — the 12 macOS presets live in a separate
\`macosLightPresets\` object and are NOT reachable by label here (see \`tucu://tokens\`).

**Known type quirk:** the \`brandColor\` prop's \`PresetColorType\` union
(\`ui/tucu-ui/src/themes/config/index.ts\`) is legacy — it names labels like
\`'Azure'\`/\`'Turquoise'\`/\`'Lime'\`/\`'Black'\` that do not exist in the real
\`PRESET_LABEL_COLORS\` enum. Stick to labels you can see in
\`colorPreset\` (\`Blue\`, \`Green\`, \`Orange\`, \`Gray\`, \`Indigo\`, \`Pink\`, \`Purple\`,
\`Red\`, \`Teal\`, \`Yellow\`, \`Chartreuse\` and their \`Dark*\`/\`Default*\` variants).

## Branding pattern: per-app vs. centralized

Two valid ways to apply \`customPaletteColor\` across a multi-app product, both directly
supported by the prop being a plain object:

- **Per-app**: each app passes its own literal \`customPaletteColor\` object to its own
  \`ThemeProvider\` mount. Simple, but a rebrand means editing every app.
- **Centralized**: define one \`customPaletteColor\` object (and \`logo\`/\`collapsedLogo\`)
  in a shared module and spread it into every app's \`ThemeProvider\`. A rebrand becomes
  a one-file change. tucu-ui has no built-in "branding registry" — the shared module is
  entirely consumer-owned; \`ThemeProvider\` just needs the same object shape on every
  mount.

## Logo, and \`collapsedLogo\`

\`logo\` (\`LogoPropTypes\`: \`name?\`, \`secondName?\`, \`path?\`, \`preset?\`, \`className?\`,
\`size?\`, \`logo?: ReactNode\`, \`isoType?\` —
\`ui/tucu-ui/src/components/logos/logo.tsx\`) is rendered by \`AdminHeader\` and
\`ExpandableSidebar\`. \`ExpandableSidebar\` also accepts \`collapsedLogo?: LogoPropTypes\`
(\`ui/tucu-ui/src/components/layouts/menus/expandable-sidebar.tsx\`, forwarded by
\`AdminLayout\` as \`collapsedLogo\`): when the rail is collapsed, it renders
\`collapsedLogo\` if provided, falling back to \`logo\` rendered with \`isoType\`
(icon-only) when omitted. Use \`collapsedLogo\` when your full logo doesn't reduce to a
legible mark at rail width — pass a dedicated compact mark instead of relying on the
automatic \`isoType\` fallback.

Note: \`LogoPropTypes.preset\` is declared on the interface but the \`Logo\` component
never reads it (\`logo.tsx\` destructures every prop except \`preset\`) — passing it has
no effect today.

## Backgrounds

\`backgroundVariant\` drives a decorative full-viewport layer rendered by
\`ThemeBackground\` behind every layout. Variants:

| Variant | Rendering |
|---------|-----------|
| none | No background layer at all |
| base, sonoma, radial, window, aurora, depth, demo | Pure CSS (gradients / materials) |
| wave, wallpaper, mobile | CSS class + an SVG image loaded from CDN (theme-aware: \`dark-\`/\`light-\` prefixed asset per mode) |

\`\`\`tsx
const { backgroundVariant, setBackgroundVariant } = useTheme();
setBackgroundVariant('wallpaper');

// Standalone usage (custom layouts):
import { ThemeBackground } from '@e-burgos/tucu-ui';
<ThemeBackground mode="fixed">{content}</ThemeBackground>      // reads the store
<ThemeBackground mode="absolute" variant="aurora" />            // explicit override
\`\`\`

Self-hosted assets: pass \`cdnBase\` to ThemeBackground to serve the SVG
variants from your own origin instead of jsDelivr.

## Theme Variants
| Variant | Description |
|---------|-------------|
| default | Standard design system |
| macos | Apple Sonoma-inspired with vibrancy, blur materials |
| macos-tahoe | Apple Tahoe-inspired with rounded corners, modern UI |

\`\`\`tsx
const { colorScheme } = useTheme(); // 'default' | 'macos' | 'macos-tahoe'
const { applyMacOSTheme } = useTheme();
applyMacOSTheme(); // applies colors + MACOS_TAHOE layout
\`\`\`

## Color Token Semantics
| Token | Light Mode Label | Dark Mode Label | Purpose |
|-------|-----------------|-----------------|---------|
| primary | Primary (Brand) Color | Dark Primary (Brand) Color | Main brand color |
| secondary | Auxiliary Background Color | Dark Auxiliary Background Color | Secondary backgrounds |
| accent | Secondary (Accent) Color | Dark Secondary (Accent) Color | Accent highlights |
| muted | Muted Color | Dark Muted Color | Muted/disabled elements |
| darkBg | — | Dark Primary Background Color | Dark mode main bg |
| lightBg | Light Primary Background Color | — | Light mode main bg |
| lightDark | Light Secondary Background Color | — | Light mode secondary bg |
| darkLightDark | — | Dark Secondary Background Color | Dark mode secondary bg |
| success / warning / error / info | Status colors | Status colors (dark) | Alert/Badge/Toast variants (info: see the blast-radius caveat above) |
| fg / border | Foreground / Border | Foreground / Border (dark) | Default text color / default border color |
`;
}
